from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="elfscope",
        description="Static ELF triage for defensive reverse engineering.",
    )
    parser.add_argument("file", help="ELF file to inspect")
    parser.add_argument("--json", dest="json_path", metavar="PATH", help="write the full report as JSON")
    parser.add_argument("--markdown", dest="markdown_path", metavar="PATH", help="write a Markdown report")
    parser.add_argument("--strings", dest="string_limit", type=int, default=100, help="maximum ASCII strings to include (default: 100)")
    parser.add_argument("--min-string", dest="string_minimum", type=int, default=6, help="minimum ASCII string length (default: 6)")
    parser.add_argument("--compact", action="store_true", help="print compact JSON instead of the human report")
    parser.add_argument("--version", action="version", version=__version__)
    return parser


def _status(value: object) -> str:
    if value in {"enabled", "full", "present"}:
        return "YES"
    if value in {"disabled", "none", "not-detected"}:
        return "NO"
    return str(value).upper()


def _render_text(report: dict) -> str:
    file_info = report["file"]
    elf = report["elf"]
    security = report["security"]
    stats = report["statistics"]
    signals = report["signals"]
    symbols = report["symbols"]

    lines = [
        "ELFscope",
        "Static ELF triage for defensive reverse engineering",
        "═" * 62,
        f"File        : {file_info['path']}",
        f"Size        : {file_info['size']} bytes",
        f"SHA-256     : {file_info['hashes']['sha256']}",
        "",
        "ELF",
        f"  Class     : ELF{elf['header']['class']}",
        f"  Data      : {elf['header']['data']}",
        f"  Type      : {elf['header']['type']} ({elf['header']['type_name']})",
        f"  Machine   : {elf['header']['machine_name']}",
        f"  Entry     : 0x{elf['header']['entry']:x}",
        f"  Interpreter: {elf['interpreter'] or 'none'}",
        "",
        "Hardening",
        f"  RELRO     : {_status(security['relro'])}",
        f"  NX        : {_status(security['nx'])}",
        f"  PIE       : {_status(security['pie'])}",
        f"  Canary    : {_status(security['stack_canary'])}",
        f"  Fortify   : {security['fortify']['checked_imports']} checked imports",
        f"  RPATH     : {', '.join(security['rpath']) if security['rpath'] else 'none'}",
        f"  RUNPATH   : {', '.join(security['runpath']) if security['runpath'] else 'none'}",
        "",
        "Statistics",
        f"  Sections  : {stats['section_count']}",
        f"  Segments  : {stats['segment_count']}",
        f"  Imports   : {stats['import_count']}",
        f"  Exports   : {stats['export_count']}",
        f"  Libraries : {stats['needed_libraries']}",
        f"  Entropy   : {stats['overall_entropy']:.3f}/8.000",
    ]

    if symbols["interesting_imports"]:
        lines += ["", "Interesting imports"]
        for name, reason in symbols["interesting_imports"].items():
            lines.append(f"  - {name}: {reason}")

    if signals:
        lines += ["", "Signals"]
        for item in signals:
            lines.append(f"  [{item['severity'].upper():7}] {item['code']}: {item['message']}")

    lines.append("")
    lines.append("Note: signals are triage hints, not proof of maliciousness or vulnerability.")
    return "\n".join(lines)


def _render_markdown(report: dict) -> str:
    file_info = report["file"]
    elf = report["elf"]
    security = report["security"]
    stats = report["statistics"]
    symbols = report["symbols"]
    signals = report["signals"]
    lines = [
        "# ELFscope report",
        "",
        f"Generated by ELFscope {report['tool']['version']}",
        "",
        "## File",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Path | `{file_info['path']}` |",
        f"| Size | {file_info['size']} bytes |",
        f"| MD5 | `{file_info['hashes']['md5']}` |",
        f"| SHA-1 | `{file_info['hashes']['sha1']}` |",
        f"| SHA-256 | `{file_info['hashes']['sha256']}` |",
        "",
        "## ELF metadata",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Class | ELF{elf['header']['class']} |",
        f"| Endianness | {elf['header']['data']} |",
        f"| Type | {elf['header']['type']} ({elf['header']['type_name']}) |",
        f"| Machine | {elf['header']['machine_name']} |",
        f"| Entry | `0x{elf['header']['entry']:x}` |",
        f"| Interpreter | `{elf['interpreter'] or 'none'}` |",
        "",
        "## Hardening",
        "",
        f"| Check | Result |",
        f"|---|---|",
        f"| RELRO | `{security['relro']}` |",
        f"| NX | `{security['nx']}` |",
        f"| PIE | `{security['pie']}` |",
        f"| Stack canary | `{security['stack_canary']}` |",
        f"| Fortify imports | {security['fortify']['checked_imports']} |",
        f"| RPATH | `{'; '.join(security['rpath']) or 'none'}` |",
        f"| RUNPATH | `{'; '.join(security['runpath']) or 'none'}` |",
        "",
        "## Statistics",
        "",
        f"- Sections: {stats['section_count']}",
        f"- Segments: {stats['segment_count']}",
        f"- Imports: {stats['import_count']}",
        f"- Exports: {stats['export_count']}",
        f"- Needed libraries: {stats['needed_libraries']}",
        f"- Whole-file entropy: {stats['overall_entropy']:.3f}/8.000",
        "",
        "## Signals",
        "",
    ]
    if signals:
        for item in signals:
            lines.append(f"- **{item['severity']}** `{item['code']}`: {item['message']}")
    else:
        lines.append("- No triage signals were raised.")

    lines += ["", "## Interesting imports", ""]
    if symbols["interesting_imports"]:
        for name, reason in symbols["interesting_imports"].items():
            lines.append(f"- `{name}`: {reason}")
    else:
        lines.append("- None detected.")

    lines += ["", "## Strings", ""]
    for value in report["strings"]:
        lines.append(f"- `{value.replace('`', '\\`')}`")
    if not report["strings"]:
        lines.append("- No printable ASCII strings matched the configured threshold.")

    lines += ["", "## Limitations", "", "This report is static and heuristic. It does not execute the target file, perform sandboxing, decompilation, control-flow recovery, or dynamic behavioural attribution.", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    from .analysis import analyse
    try:
        report = analyse(args.file, string_limit=max(0, args.string_limit), string_minimum=max(3, args.string_minimum))
    except FileNotFoundError as exc:
        print(f"elfscope: file not found: {exc}", file=sys.stderr)
        return 2
    except (ValueError, OSError) as exc:
        print(f"elfscope: {exc}", file=sys.stderr)
        return 2

    if args.json_path:
        destination = Path(args.json_path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(json.dumps(report, indent=2, sort_keys=False) + "\n", encoding="utf-8")

    if args.markdown_path:
        destination = Path(args.markdown_path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(_render_markdown(report), encoding="utf-8")

    if args.compact:
        print(json.dumps(report, separators=(",", ":")))
    else:
        print(_render_text(report))
    return 0
